name: Update Readme for my Github Profile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Node Step Youtube
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
      - run: npm install
      - run: npm run update-readme
      - run: |
          git config user.name trabajayacomodeveloper
          git add README.md
          git commit -m "[from github Action] Update Readme with latest news"
          git push origin main